import { PhilosophyPageBlueprint } from '@/types/philosophySection';

/**
 * Nexus LAB AI — Canonical Philosophy Page Architecture Blueprint
 * Phase 04E.4 — 12-Section Epistemic Narrative & Systems Blueprint
 */
export const PHILOSOPHY_PAGE_BLUEPRINT: PhilosophyPageBlueprint = {
  pageId: 'philosophy',
  route: '/philosophy',
  title: 'Nexus LAB AI Philosophy Track',
  description:
    'First-Principles Epistemological & Cognitive Foundations for Verifiable Machine Intelligence — Investigating classical Indian theories of knowledge, cognition, agency, and responsibility to motivate modern AI research hypotheses and computational architectures.',
  sections: [
    {
      order: 1,
      id: 'philosophy-hero',
      title: 'First-Principles Foundations for Verifiable Intelligence',
      eyebrow: 'Nexus LAB AI Philosophy',
      purpose:
        'Establish the institutional Philosophy identity: investigating classical Indian epistemological, cognitive, and normative systems to establish computational architectures for verifiable machine intelligence without historical anachronism.',
      sourceAuthority: 'TIER_1_CONSTITUTIONAL / 04E.2_AUTHORITATIVE_REGISTER',
      componentType: 'PhilosophyHeroSection',
      containerWidth: 'full',
      background: 'primary',
      spacing: 'none',
      contentKey: 'identity',
      dataSource: 'CANONICAL_PHILOSOPHY_REGISTRY',
    },
    {
      order: 2,
      id: 'philosophy-thesis',
      title: 'The Shastra–AI Integration Methodology',
      eyebrow: 'Epistemic Framework',
      purpose:
        'Articulate the unidirectional research pipeline: extracting classical philosophical inquiries, formulating modern interpretations, constructing testable AI hypotheses, and building verified computational systems.',
      sourceAuthority: 'TIER_1_CONSTITUTIONAL / 04E.2_AUTHORITATIVE_REGISTER',
      componentType: 'PhilosophyThesisSection',
      containerWidth: 'content',
      background: 'secondary',
      spacing: 'md',
      contentKey: 'identity',
      dataSource: 'CANONICAL_PHILOSOPHY_REGISTRY',
    },
    {
      order: 3,
      id: 'philosophy-principles',
      title: 'The Eight Foundational Principles',
      eyebrow: 'Public Epistemic Constitution',
      purpose:
        'Present the eight authoritative public philosophy principles structured through philosophical foundation, modern Nexus interpretation, and concrete engineering consequence.',
      sourceAuthority: 'TIER_1_CONSTITUTIONAL / 04E.2_AUTHORITATIVE_REGISTER',
      componentType: 'PhilosophyPrinciplesSection',
      containerWidth: 'wide',
      background: 'primary',
      spacing: 'lg',
      contentKey: 'principles',
      dataSource: 'getPublicPhilosophyPrinciples',
    },
    {
      order: 4,
      id: 'philosophy-epistemology',
      title: 'Epistemic Grounding & Knowledge Validation',
      eyebrow: 'Pramāṇa-Śāstra',
      purpose:
        'Explore how knowledge is acquired and validated: Pramāṇa source tagging, Pañcāvayava five-step structured syllogism, intrinsic vs extrinsic validity (Prāmāṇya), and Khyātivāda error taxonomies.',
      sourceAuthority: '01.02_EPISTEMOLOGY / 04E.2_AUTHORITATIVE_REGISTER',
      componentType: 'PhilosophyEpistemologySection',
      containerWidth: 'wide',
      background: 'secondary',
      spacing: 'lg',
      contentKey: 'concepts',
      dataSource: 'getPublicPrimaryConcepts',
    },
    {
      order: 5,
      id: 'philosophy-cognition',
      title: 'Cognitive Architecture & Latent Memory',
      eyebrow: 'Antaḥkaraṇa & Citta',
      purpose:
        'Examine the multi-tier internal cognitive stack: sensory routing (Manas), ego-frame (Ahaṃkāra), determinative judgment (Buddhi), and persistent latent trace retrieval (Saṃskāra & Smṛti).',
      sourceAuthority: '01.03_COGNITION / 04E.2_AUTHORITATIVE_REGISTER',
      componentType: 'PhilosophyCognitionSection',
      containerWidth: 'wide',
      background: 'primary',
      spacing: 'lg',
      contentKey: 'concepts',
      dataSource: 'getPublicPrimaryConcepts',
    },
    {
      order: 6,
      id: 'philosophy-agency',
      title: 'Material Functionalism & Computational Agency',
      eyebrow: 'Prakṛti & Kartṛtva',
      purpose:
        'Deconstruct agency and volition from a radical dualist perspective: computational intelligence operates entirely in physical matter (Prakṛti) without requiring subjective conscious sentience (Puruṣa).',
      sourceAuthority: '01.04_AGENCY / 04E.2_AUTHORITATIVE_REGISTER',
      componentType: 'PhilosophyAgencySection',
      containerWidth: 'content',
      background: 'secondary',
      spacing: 'lg',
      contentKey: 'concepts',
      dataSource: 'getPublicPrimaryConcepts',
    },
    {
      order: 7,
      id: 'philosophy-responsibility',
      title: 'Normative Governance & Duty Boundaries',
      eyebrow: 'Dharma & Adhikāra',
      purpose:
        'Establish contextual agent safety: Svadharma role-scoped constraints, Dharma-saṅkaṭa dilemma resolution hierarchies, and Adhikāra pre-flight capability authorization gating.',
      sourceAuthority: '01.05_RESPONSIBILITY / 04E.2_AUTHORITATIVE_REGISTER',
      componentType: 'PhilosophyResponsibilitySection',
      containerWidth: 'wide',
      background: 'primary',
      spacing: 'lg',
      contentKey: 'concepts',
      dataSource: 'getPublicPrimaryConcepts',
    },
    {
      order: 8,
      id: 'philosophy-formalization',
      title: 'The Formalization Frontier',
      eyebrow: 'Computational Tractability',
      purpose:
        'Define the three zones of computational formalization: Computationally Representable, Computationally Approximable, and Philosophically Open boundaries.',
      sourceAuthority: '01.06_FORMALIZATION / 04E.2_AUTHORITATIVE_REGISTER',
      componentType: 'PhilosophyFormalizationSection',
      containerWidth: 'content',
      background: 'secondary',
      spacing: 'md',
      contentKey: 'concepts',
      dataSource: 'CANONICAL_PHILOSOPHY_REGISTRY',
    },
    {
      order: 9,
      id: 'philosophy-hypotheses',
      title: 'AI Research Hypotheses',
      eyebrow: 'Testable Conjectures',
      purpose:
        'Catalog the testable computational conjectures derived from classical Indian philosophy, explicitly distinguishing hypotheses from proven scientific facts.',
      sourceAuthority: '01.07_AI_HYPOTHESES / 04E.2_AUTHORITATIVE_REGISTER',
      componentType: 'PhilosophyHypothesesSection',
      containerWidth: 'wide',
      background: 'primary',
      spacing: 'lg',
      contentKey: 'hypotheses',
      dataSource: 'CANONICAL_PHILOSOPHY_REGISTRY',
    },
    {
      order: 10,
      id: 'philosophy-mapping',
      title: 'Nexus Architectural Alignment Matrix',
      eyebrow: 'Grounded Systems Mapping',
      purpose:
        'Map philosophical concepts to active Nexus systems (NALA, AMP, RTA-GUARD, CHAITANYA) across controlled relationship tiers (Direct, Research, Analogy, Naming, None).',
      sourceAuthority: '01.08_NEXUS_MAPPING / 04E.2_AUTHORITATIVE_REGISTER',
      componentType: 'PhilosophyMappingSection',
      containerWidth: 'wide',
      background: 'secondary',
      spacing: 'lg',
      contentKey: 'concepts',
      dataSource: 'getPublicPrimaryConcepts',
    },
    {
      order: 11,
      id: 'philosophy-boundaries',
      title: 'Epistemic Firewall & Explicit Non-Claims',
      eyebrow: 'Epistemic Safeguards',
      purpose:
        'Expose the public epistemic firewall: master quarantined claims, non-claims, and negative boundaries declaring what Nexus LAB AI does NOT claim.',
      sourceAuthority: '04E.2_AUTHORITATIVE_REGISTER',
      componentType: 'PhilosophyBoundariesSection',
      containerWidth: 'content',
      background: 'primary',
      spacing: 'lg',
      contentKey: 'quarantinedClaims',
      dataSource: 'getQuarantinedClaims',
    },
    {
      order: 12,
      id: 'philosophy-closing',
      title: 'Long-Horizon Philosophical Trajectory',
      eyebrow: 'Systems Exploration',
      purpose:
        'Conclude with the institutional research trajectory and navigation pathways across Overview, Research, Technology, and Programs.',
      sourceAuthority: 'TIER_1_CONSTITUTIONAL',
      componentType: 'PhilosophyClosingSection',
      containerWidth: 'narrow',
      background: 'secondary',
      spacing: 'lg',
      contentKey: 'identity',
      dataSource: 'CANONICAL_PHILOSOPHY_REGISTRY',
    },
  ],
};
